// src/Events.ts

// Define all event names as constants
export const AnalyticsEvents = {
  Activated: "Extension Activated",
  BackArrowClicked: "BackArrowClicked",
  GithubIconClicked: "GithubIconClicked",
  GithubLoginButtonlicked: "LoginWithGithub clicked",
  UserLoggedInSuccessfully: "UserLoggedInSuccessfully",
  UserSignedUPSuccessfully: "UserSignedUpSuccessfully",
  UserLoggedInFailed: "UserLoggedInFailed",
  SymmetryNetworkSettingsClicked: "SymmetryNetworkSettingsClicked",
  ManageProvidersClicked: "ManageProvidersClicked",
  ManageTemplatesClicked: "ManageTemplatesClicked",
  EditTemplatesClicked: "EditTemplatesClicked",
  ConversationHistoryClicked: "ConversationHistoryClicked",
  StartNewChatClicked: "StartNewChatClicked",
  SettingsClicked: "DevdockSettingsClicked",
  CPToggleButtonClicked: "CPToggleButtonClicked",
  CPGenerateCommitClicked: "CPGenerateCommitClicked",
  CPScrollDownClicked: "CPScrollDownClicked",
  CPisRAGContextClickedEnabled: "CPisRAGContextClickedEnabled",
  CPEmbeddingOptionsClicked: "CPEmbeddingOptionsClicked",
  CPSelectActiveProvidersClicked: "CPSelectActiveProvidersClicked",
  CPChatQuerySubmitClicked: "CPChatQuerySubmitClicked",
  BOUNTY_CREATED: "BountyCreated",
  BOUNTY_CREATE_POPUP_SHOWN: "BountyCreationPopUpOpened",
  BOUNTY_SUBMITTED: "BountySubmitted",
  BOUNTY_VISIBILITY_BANNER_SHOWN: "BountyBannerShown",
  BOUNTY_VISIBILITY_BANNER_CLICKED: "BountyBannerClicked",
  USER_QUERY_FOR_CHAIN_AND_CONTENT: "UserQueryForChain",
  BOUNTY_SUBMISSION_SUPPORTING_FILES_GENERATED: "SupportingFilesGenerated",
};
